### PR TITLE
Qgep swmm phase3 enhancements

### PR DESCRIPTION
**Pull request by tproduit**
* notify user from qgep_swmm views
* import backflow_level and hydraulic_load
* export selection
* new tool to set default coefficient of friction

### CODE REVIEW

**Comment by ponceta** [comment]
Datamodel is ready for this.

**Comment by ponceta** [comment]
@olivierdalang can we merge this?

**Comment by olivierdalang** [comment]
> @olivierdalang can we merge this?

Hard for me to review SWMM related work, since I'm not familiar with the workflows. But IMO we can merge since it's not too risky (quite isolated changes from the test).

About the merge itself, not sure why github can't merge this, and since it's on your repo @tproduit I can't directly push, but opened a PR here: https://github.com/iggroup/qgepplugin/pull/10 to fix the conflict. Otherwise I'll open another PR instead.

**Comment by olivierdalang** [comment]
Not exactly sure of what I did (seems I got confused with some merges), but this is now merged in master (https://github.com/QGEP/qgepplugin/commit/5048b01ab93bc29fe76c99440c34de181f8e971a)

**Pull request closed without merging**
