### PR TITLE
Add processing algorithm to reverse reaches

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by max-trolliet** [comment]
Everything goes smoothly in the Consol until 

>>> transaction.executeSql('SELECT qgep_od.reach_direction_change(\'{{{obj_ids}}}\');'.format(obj_ids=','.join(selected_obj_ids)))

Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'executeSql'

**Comment by m-kuhn** [comment]
Weird, this works for me.

1. select vw_qgep_reach layer
2. run the following snippet:

```
layer = iface.activeLayer()
layer.startEditing()
transaction = layer.dataProvider().transaction()
print(transaction)
transaction.executeSql('SELECT 1')
```

**Comment by m-kuhn** [comment]
Latest version works for me with the new function in the database model

**Comment by max-trolliet** [comment]
in the console or with the processing? 

I'm stuck with the same error. Am I doing smth wrong?

**Comment by m-kuhn** [comment]
In processing.

**Comment by max-trolliet** [comment]
Can you send me the two .py provider and change_reach_direction?

**Comment by max-trolliet** [comment]
Did you change anything else? I took those two and put them in the folder.... but then QGIS can no longer load the plugin.

**Comment by m-kuhn** [comment]
I see, some other file is missing. Either download the whole processing_provider folder from github or wait for the next release.

**Comment by m-kuhn** [comment]
Depends on https://github.com/QGEP/datamodel/pull/81

**Comment by max-trolliet** [comment]
Just took the whole folder and retried the console : 

layer = iface.activeLayer()
layer.startEditing()
transaction = layer.dataProvider().transaction()
print(transaction)
transaction.executeSql('SELECT 1')

Gives me : 
layer = iface.activeLayer()
layer.startEditing()
True
transaction = layer.dataProvider().transaction()
print(transaction)
None
transaction.executeSql('SELECT 1')
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python36\lib\code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'executeSql'

**Comment by max-trolliet** [comment]
Okey, 1.1.3 is working..... but it is not possible to save the modifications... When I close the editing mode... all the modified reaches get back to the initial state.

**Comment by m-kuhn** [comment]
@max-trolliet, if you modify something else after the algorithm and save then, is it better?

**Comment by max-trolliet** [comment]
Yes that does the trick. I tried to digitize a fake new reach after using the processing. The save button can then be used and the modifications are saved in base.

**Comment by m-kuhn** [comment]
Thanks, can you open a new issue for this?
We are blocked on development at the moment but will fix this as soon as we get the go ahead.

**Pull request merged**
